app_accounts/urls.py
from django.urls import path
from app_accounts.views import signup, login_view, logout_view

app_name = 'app_accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

app_admin_management/urls.py
from django.urls import path
from app_admin_management.views import index_admin, user_data_from_excel

app_name = 'app_admin_management'

urlpatterns = [
    path('index_admin/', index_admin, name='index_admin'),
    path('user_data_from_excel/', user_data_from_excel, name='user_data_from_excel'),
]

tg_kiberclub/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kiberclub/', include('app_kiberclub.urls')),
    path('accounts/', include('app_accounts.urls')),
    path('admin_management/', include('app_admin_management.urls')),
    path('kibershop/', include('app_kibershop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_admin_management/models.py
from django.db import models

# Create your models here.

app_admin_management/forms.py
from django import forms
from app_kiberclub.models import Locations

class UploadExcelFileForm(forms.Form):
    file = forms.FileField()
    location_name = forms.ChoiceField(
        choices=[(location['location_name'], location['location_name']) for location in
                 Locations.objects.values('location_name').distinct()],
        label="Location Name"
    )
    sheet_url = forms.ChoiceField(
        choices=[(location['sheet_url'], location['sheet_url']) for location in
                 Locations.objects.values('sheet_url').distinct()],
        label="Sheet URL"
    )
    sheet_names = forms.ChoiceField(
        choices=[(location['sheet_names'], location['sheet_names']) for location in
                 Locations.objects.values('sheet_names').distinct()],
        label="Sheet Names"
    )

app_admin_management/views.py
import os

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import gspread
import pandas as pd
import logging
from app_admin_management.forms import UploadExcelFileForm
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile




logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s - %(lineno)d - %(message)s'
)

CREDENTIALS_FILE = 'kiberone-tg-bot-a43691efe721.json'


def index_admin(request):
    return render(request, 'app_admin_management/index_admin.html')


def user_data_from_excel(request):
    if request.method == 'POST':
        form = UploadExcelFileForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['file']
            file_path = default_storage.save('tmp/' + excel_file.name, ContentFile(excel_file.read()))
            tmp_file = os.path.join(default_storage.location, file_path)
            location_name = form.cleaned_data['location_name']
            sheet_url = form.cleaned_data['sheet_url']
            sheet_names = form.cleaned_data['sheet_names']

            # обработка
            excel_df = pd.read_excel(excel_file)
            google_sheet = GoogleSheet(CREDENTIALS_FILE, sheet_url, sheet_names)
            google_sheet.add_new_rows(excel_df)

            default_storage.delete(file_path)

            messages.success(request, 'File uploaded and processed successfully!', extra_tags='success')
            return redirect('app_admin_management:user_data_from_excel')

        else:
            messages.error(request, 'File upload failed!', extra_tags='danger')
            return redirect('app_admin_management:user_data_from_excel')
    else:
        form = UploadExcelFileForm()
    return render(request, 'app_admin_management/user_data_from_excel.html', {'form': form})



# Настройка логирования


class GoogleSheet:
    def __init__(self, google_credentials_file: str, spreadsheet_url: str, worksheet_name: str) -> None:
        try:
            self.account = gspread.service_account(filename=google_credentials_file)
            self.spreadsheet = self.account.open_by_url(spreadsheet_url)
            self.worksheet = self.spreadsheet.worksheet(worksheet_name)
        except Exception as e:
            logging.error(f"Ошибка подключения к Google Sheets: {e}")
            raise e

    def get_existing_ids(self) -> set:
        """Загружает существующие ID из Google Sheets для быстрого сравнения."""
        try:
            column_values = self.worksheet.col_values(1)  # Получаем только первый столбец (ID)
            return set(column_values[1:])  # Пропускаем заголовок
        except Exception as e:
            logging.error(f"Ошибка при загрузке ID из Google Sheets: {e}")
            return set()

    def add_new_rows(self, excel_df: pd.DataFrame):
        """Добавляет новые строки из Excel, если их нет в Google Sheets."""
        try:
            existing_ids = self.get_existing_ids()
            logging.info(f"Найдено {len(existing_ids)} существующих записей в Google Sheets.")

            new_rows = [
                [
                    str(row["ID"]),  # ID ребенка
                    row["ФИО"],      # ФИО ребенка
                    row["Группы"],   # Группа
                    "", "", "", ""   # Пустые колонки для резюме и отзыва
                ]
                for _, row in excel_df.iterrows() if str(row["ID"]) not in existing_ids
            ]

            if new_rows:
                self.worksheet.append_rows(new_rows, value_input_option="RAW")
                logging.info(f"Добавлено {len(new_rows)} новых строк в Google Sheets.")
            else:
                logging.info("Нет новых данных для добавления.")
        except Exception as e:
            logging.error(f"Ошибка при добавлении новых данных: {e}")
            raise e

templates/app_admin_management/index_admin.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/admin_styles.css' %}">
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Admin Home Page</h1>
    {% if user.is_authenticated %}
        <h2>Hello, {{ user.username }}!</h2>
        <p><a href="{% url 'app_admin_management:user_data_from_excel' %}">Загрузить данные учеников для локации</a></p>
        <a href="{% url 'app_accounts:logout' %}">Logout</a>
    {% else %}
        <p><a href="{% url 'app_accounts:login' %}">Login</a></p>
        <p><a href="{% url 'app_accounts:signup' %}">Sign Up</a></p>
    {% endif %}
</body>
</html>

templates/app_admin_management/user_data_from_excel.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/admin_styles.css' %}">


<!DOCTYPE html>
<html>
<head>
    <title>Upload Excel File</title>
</head>
<body>
<h2>Upload Excel File</h2>
<p>Загрузите файл с данными учеников конкретной локации, чтобы добавить их в файл резюме от тьюторов</p>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
<script>
    // scripts.js
    document.addEventListener('DOMContentLoaded', function () {
        // Получаем все сообщения
        var messages = document.querySelectorAll('.messages li');

        // Перебираем все сообщения и устанавливаем таймер для их скрытия
        messages.forEach(function (message) {
            setTimeout(function () {
                message.style.display = 'none';
            }, 3000); // 3 секунды
        });
    });

</script>
</body>
</html>