app_accounts/urls.py
from django.urls import path
from app_accounts.views import signup, login_view, logout_view

app_name = 'app_accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

app_kiberclub/urls.py
from django.urls import path

from app_kiberclub.views import open_profile, choose_child, save_init_data, index, error_page, submit_review

app_name = 'app_kiberclub'

urlpatterns = [
    path('index/', index, name='index'),
    path('save_init_data/', save_init_data, name='save_init_data'),
    path('choose_child/', choose_child, name='choose_child'),
    path('profile/', open_profile, name='open_profile'),
    path('error/', error_page, name='error_page'),
    path('review_from_parent/', submit_review, name='review_from_parent'),
]

app_kibershop/urls.py
from django.urls import path
from app_kibershop.views import catalog, add_to_cart, cart, remove_from_cart, cart_plus, cart_minus, make_order, profile_page


app_name = 'app_kibershop'


urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', cart, name='cart'),
    path('remove_from_cart/<int:cart_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart_plus/<int:cart_id>/', cart_plus, name='cart_plus'),
    path('cart_minus/<int:cart_id>/', cart_minus, name='cart_minus'),
    path('make_order/', make_order, name='make_order'),
    path('profile_page/', profile_page, name='profile_page'),
]

tg_kiberclub/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kiberclub/', include('app_kiberclub.urls')),
    path('accounts/', include('app_accounts.urls')),
    path('admin_management/', include('app_admin_management.urls')),
    path('kibershop/', include('app_kibershop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_kiberclub/models.py
from django.db import models


class UserData(models.Model):
    tg_id = models.CharField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=255, blank=True, null=True)
    is_study = models.IntegerField(blank=True, null=True)
    balance = models.CharField(max_length=255, blank=True, null=True)
    paid_lesson_count = models.IntegerField(blank=True, null=True)
    next_lesson_date = models.CharField(max_length=255, blank=True, null=True)
    user_branch_ids = models.CharField(max_length=255, blank=True, null=True)
    user_crm_id = models.IntegerField(blank=True, null=True)
    notified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    customer_data = models.TextField(blank=True, null=True)
    kiberons_count = models.IntegerField(default=0, null=True, blank=True)
    kiberons_count_after_orders = models.IntegerField(default=0, null=True, blank=True)
    user_lessons = models.BooleanField(default=False, null=True, blank=True)

    objects = models.Manager()

    class Meta:
        managed = True
        db_table = 'users'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f"user: {self.username or self.tg_id}"

class Locations(models.Model):
    id = models.IntegerField(primary_key=True)
    location_branch_id = models.IntegerField()
    location_id = models.IntegerField()
    location_name = models.CharField(max_length=255)
    location_map_link = models.CharField(max_length=255)
    sheet_url = models.CharField(max_length=255)
    sheet_names = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = True
        db_table = 'Locations'
        verbose_name = 'Локация'
        verbose_name_plural = 'Локации'

    def __str__(self):
        return self.location_name

class BranchesTelegramLink(models.Model):
    branch_id = models.IntegerField()
    link = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'branches_telegram_link'
        verbose_name = 'Телеграм ссылка на бранч'
        verbose_name_plural = 'Телеграм ссылки на бранч'

    def __str__(self):
        return str(self.branch_id)

class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'FAQ'
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'

    def __str__(self):
        return self.question

class Promotion(models.Model):
    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'Promotion'
        verbose_name = 'Промо акция'
        verbose_name_plural = 'Промо акции'

    def __str__(self):
        return self.question

class PartnerCategory(models.Model):
    category = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'PartnerCategory'
        verbose_name = 'Категория партнера'
        verbose_name_plural = 'Категории партнеров'

    def __str__(self):
        return self.category

class Partner(models.Model):
    partner = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(PartnerCategory, on_delete=models.CASCADE, related_name='partners')

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'Partner'
        verbose_name = 'Партнер'
        verbose_name_plural = 'Партнеры'

    def __str__(self):
        return self.partner

class Link(models.Model):
    link_name = models.CharField(max_length=255)
    link_url = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'Link'
        verbose_name = 'Ссылка на соц сеть'
        verbose_name_plural = 'Ссылки на соц сети'

    def __str__(self):
        return self.link_name

class Manager(models.Model):
    branch = models.IntegerField()
    location = models.IntegerField()
    manager = models.CharField(max_length=255)
    link = models.CharField(max_length=255)

    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'Manager'
        verbose_name = 'Менеджер'
        verbose_name_plural = 'Менеджеры'

    def __str__(self):
        return self.manager

app_kiberclub/views.py
import json
import hashlib
import hmac
from urllib import parse
import os
from hmac import new as hmac_new
import pandas as pd

import gspread
import requests
from bs4 import BeautifulSoup
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from urllib.parse import unquote
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from dotenv import load_dotenv
from gspread import GSpreadException

from app_kiberclub.alfa_crm import find_user_by_phone, get_client_lessons, get_client_lesson_name
from app_kiberclub.models import UserData, Locations


from logger_config import get_logger

logger = get_logger()


load_dotenv()

DEBUG = os.environ.get("BOT_DEBUG")
if DEBUG == "dev":
    BOT_TOKEN = os.environ.get("BOT_TOKEN2")
else:
    BOT_TOKEN = os.environ.get("BOT_TOKEN")

CREDENTIALS_FILE = 'kiberone-tg-bot-a43691efe721.json'

class GoogleSheet:
    def __init__(self, google_credentials_file: str, spreadsheet_url: str, worksheet_name: str) -> None:
        try:
            self.account = gspread.service_account(filename=google_credentials_file)
            self.spreadsheet = self.account.open_by_url(spreadsheet_url)
            self.worksheet_name = worksheet_name
            self.topics = {elem.title: elem.id for elem in self.spreadsheet.worksheets()}
            if worksheet_name not in self.topics:
                raise ValueError(f"Worksheet '{worksheet_name}' not found in spreadsheet")
            self.worksheet = self.spreadsheet.get_worksheet_by_id(self.topics[worksheet_name])
        except Exception as e:
            print(f"Ошибка подключения к Google Sheets: {e}")
            raise e

    def load_data_from_google_sheet(self) -> pd.DataFrame:
        """Загружает данные из Google Sheets."""
        try:
            if not self.spreadsheet:
                raise ValueError("Spreadsheet is not initialized")
            if not self.topics:
                raise ValueError("No topics found in the spreadsheet")
            worksheet = self.spreadsheet.worksheet(self.worksheet_name)
            if not worksheet:
                raise ValueError(f"Worksheet '{self.worksheet_name}' not found in spreadsheet")
            try:
                data = worksheet.get_all_records()
            except Exception as e:
                raise GSpreadException(e)
            if not data:
                raise ValueError("No data found in the worksheet")
            df = pd.DataFrame(data)
            return df
        except Exception as e:
            print(f"Ошибка загрузки данных из Google Sheets: {e}")
            raise e

    def add_data_to_google_sheet(self, user_crm_id, feedback):
        """Добавляет фидбек от родителя в Google Sheets."""
        try:
            df = self.load_data_from_google_sheet()

            row_index = df[df['ID ребенка'] == user_crm_id].index
            if row_index.empty:
                raise ValueError(f"Child with ID {user_crm_id} not found in the worksheet")

            row_number = row_index[0] + 2  # +2, потому что индексы DataFrame начинаются с 0, а индексы Google Sheets с 1
            self.worksheet.update_cell(row_number, df.columns.get_loc('Отзыв родителя') + 1, feedback)

        except Exception as e:
            print(f"Ошибка добавления данных в Google Sheets: {e}")
            raise e

    def save_data_to_google_sheet(self, df: pd.DataFrame, worksheet_name) -> None:
        """Сохраняет DataFrame в указанный лист Google Sheets."""
        try:
            if not self.spreadsheet:
                raise ValueError("Spreadsheet is not initialized")
            if not self.topics:
                raise ValueError("No topics found in the spreadsheet")
            worksheet = self.spreadsheet.worksheet(worksheet_name)
            if not worksheet:
                raise ValueError(f"Worksheet '{worksheet_name}' not found in spreadsheet")
            worksheet.clear()
            worksheet.update([df.columns.values.tolist()] + df.values.tolist())
        except Exception as e:
            raise e


def index(request):
    context = {
        'is_iphone': request.is_iphone,
        "title": "KIBERone",
    }
    return render(request, 'app_kiberclub/greetings.html', context=context)


def choose_child(request):
    user_crm_items = request.session.get('user_crm_items', [])
    if not user_crm_items:
        return redirect('app_kiberclub:error_page')
    profiles = {}
    for item in user_crm_items:
        profiles.update({item.get("id"): item.get("name")})
    context = {
        'is_iphone': request.is_iphone,
        "profiles": profiles,
    }
    return render(request, 'app_kiberclub/choose_child.html', context=context)


def error_page(request):
    context = {
        'is_iphone': request.is_iphone,
    }
    return render(request, 'app_kiberclub/error_page.html', context=context)


def get_user_crm_items(request):
    logger.debug("get_user_crm_items called")

    user_tg_id = request.session.get('user_tg_id')
    logger.debug(f"User Telegram ID from session: {user_tg_id}")

    if not user_tg_id:
        logger.error("No user_tg_id found in session.")
        return redirect('app_kiberclub:error_page')

    try:
        user_db_info = UserData.objects.filter(tg_id=user_tg_id).first()
        logger.debug(f"User database info: {user_db_info}")
    except Exception as e:
        logger.error(f"Error fetching user data from database: {e}")
        return redirect('app_kiberclub:error_page')
        # return JsonResponse({"status": "error", "message": "Ошибка при поиске записи в базе данных"}, status=404)

    if not user_db_info:
        logger.error("No user data found in the database.")
        return redirect('app_kiberclub:error_page')

    try:
        user_data_by_phone = find_user_by_phone(user_db_info.phone_number)
        logger.debug(f"User data by phone: {user_data_by_phone}")
    except Exception as e:
        logger.error(f"Error finding user by phone: {e}")
        return redirect('app_kiberclub:error_page')

    if not user_data_by_phone:
        logger.error("No user data found by phone.")
        return redirect('app_kiberclub:error_page')

    user_crm_items = user_data_by_phone.get('items')
    logger.debug(f"User CRM items: {user_crm_items}")

    return user_crm_items


# @csrf_exempt
def save_init_data(request):
    logger.debug("save_init_data called")

    if request.method == 'POST':
        logger.debug("Request method is POST")
        try:
            data = json.loads(request.body)
            logger.debug(f"Request body loaded: {data}")
        except json.JSONDecodeError as e:
            logger.error(f"Failed to decode JSON: {e}")
            return JsonResponse({"status": "error", "message": "Invalid JSON data."}, status=400)

        init_data = data.get('initData')
        if not init_data:
            logger.error("No init data received.")
            return JsonResponse({"status": "error", "message": "No init data received."}, status=400)

        secret_key = BOT_TOKEN
        logger.debug(f"Secret key: {secret_key}")

        init_data_dict = validate(init_data, secret_key)
        if init_data_dict is None:
            logger.error("Invalid data received.")
            return JsonResponse({"status": "error", "message": "Invalid data received."}, status=400)

        logger.debug(f"init_data_dict: {init_data_dict}")

        try:
            user_dict = json.loads(init_data_dict.get('user'))
            logger.debug(f"User dictionary: {user_dict}")
        except json.JSONDecodeError as e:
            logger.error(f"Failed to decode user JSON: {e}")
            return JsonResponse({"status": "error", "message": "Invalid user data."}, status=400)

        user_tg_id = user_dict.get('id')
        logger.debug(f"User Telegram ID: {user_tg_id}")
        request.session['user_tg_id'] = user_tg_id

        user_crm_items = get_user_crm_items(request)
        logger.debug(f"User CRM items: {user_crm_items}")

        if not user_crm_items:
            logger.error("No user CRM items received.")
            return redirect('app_kiberclub:error_page')

        try:
            request.session['user_crm_items'] = user_crm_items
            logger.debug("User CRM items saved to session.")
        except Exception as e:
            logger.error(f"Failed to save user CRM items to session: {e}")
            return redirect('app_kiberclub:error_page')

        return JsonResponse({'status': 'success'})

    logger.error("Invalid request method.")
    return JsonResponse({'status': 'invalid request'}, status=400)


def open_profile(request):
    context = {
        'is_iphone': request.is_iphone,
    }
    if request.method == 'POST':
        profile_id = request.POST.get('profile_id')


        user_crm_items = request.session.get('user_crm_items', [])
        if not user_crm_items:
            return redirect('app_kiberclub:error_page')

        for item in user_crm_items:
            if int(item.get('id')) == int(profile_id):
                user_crm_id = item.get("id")
                request.session['user_crm_id'] = user_crm_id
                user_crm_branch_ids = item.get("branch_ids")
                request.session['user_crm_branch_ids'] = user_crm_branch_ids
                user_crm_name = item.get("name").strip()
                user_crm_birthday = item.get("dob")

                context.update({
                    "user_crm_id": user_crm_id,
                    "user_crm_name": user_crm_name,
                    "user_tg_id": request.session.get('user_tg_id'),
                })

                lesson_name, room_id = get_user_lessons(user_crm_id, user_crm_branch_ids)
                if lesson_name and room_id:
                    context.update({
                        "lesson_name": lesson_name if lesson_name else "У вас нет занятий",
                        "room_id": room_id,
                    })
                else:

templates/app_kiberclub/choose_child.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>KIBERone</title>
    {% if is_iphone %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/choose_child_style_iphone.css' %}">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/choose_child_style.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'styles/spinner_style.css' %}">
</head>
<body>
<center>
    <div id="loader"></div>
</center>
<div id="mainDiv">
    <form action="{% url 'app_kiberclub:open_profile' %}" method="post" id="profileForm">
        {% csrf_token %}
        {% if profiles %}
            <label for="profiles">В KIBERone учится...</label>
            <select id="profiles" name="profile_id">
                {% for id, name in profiles.items %}
                    <option value="{{ id }}">{{ name }}</option>
                {% endfor %}
            </select>
            <button type="submit" id="open">Перейти в KIBERhub</button>
        {% else %}
            <p>Как бы мы не старались, но не нашли ни одного профиля.</p>
        {% endif %}
    </form>
</div>

</body>
<script>
    document.getElementById("loader").style.display = 'none';

    document.getElementById('profileForm').addEventListener('submit', function () {
        const contentElement = document.getElementById("mainDiv");
        const loaderElement = document.getElementById("loader");

        loaderElement.style.display = 'block';
        contentElement.style.display = 'none';

    });
</script>
</html>

templates/app_kiberclub/client_card.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Профиль</title>
    <link rel="stylesheet" href="{% static 'styles/client_card_style.css' %}">
    <link rel="stylesheet" href="{% static 'styles/feed_back_form_style.css' %}">
    <link rel="stylesheet" href="{% static 'styles/running_line.css' %}">

    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <link rel="stylesheet" href="{% static 'styles/feed_back_form_style.css' %}">
</head>

<body>
<div id="mainDiv">
    <div id="main">
        <section id="infoWithImage">
            <img src="{% static 'img/profile_image.png' %}" id="profileImg" alt="">
            <section id="userInfo">
                <section id="account">
                    <img src="{% static 'img/wallet_img.png' %}" id="walletImg" alt=""><b
                        id="kiberons">{{ user_kiberons }} К</b>
                </section>
                <p id="fullname" style="font-family: 'Inter Light';">{{ user_crm_name }}</p>
                <b id="dob" style="font-family: 'Inter Light';">{{ user_crm_birthday }}</b>
                <b id="location" style="font-family: 'Inter Light';">{{ user_location }}</b>
            </section>
        </section>
        <a href="{% url 'app_kibershop:catalog' %}">Перейти в KIBERshop</a>
        <div id="warning">
            <p class="warningText">ПРЕДЗАКАЗ ЗАКРЫТ! ВАШИ ЗАКАЗЫ ВЫ МОЖЕТЕ ОТСЛЕДИТЬ ПЕРЕЙДЯ ПО КНОПКЕ ПРОФИЛЯ В ШАПКЕ</p>
        </div>
        <section id="extraInfo">
            <div class="backend_info" id="backend_info"></div>
            <p>Тема следующего занятия</p>
            <span id="subject">{{ lesson_name }}</span>
            <p>Обратная связь от тьютора</p>
            <span id="resume">
                <div class="item" id="resumeInfo">
                    {{ user_resume }}
                </div>
            </span>
        </section>
        <section id="feedback">
            <i id="message">Оставьте обратную связь по работе нашей КИБЕР-школы!<br></i>
            <form id="feedbackForm" onsubmit="event.preventDefault(); submitReview();">
                {% csrf_token %}
                <textarea placeholder="Отзыв" id="feedbackInput" name="feedbackInput"></textarea>
                <div id="forSendButton">
                    <button type="submit" id="sendButton">Отправить</button>
                </div>
            </form>
        </section>
    </div>
</div>
<script>
    function submitReview() {
        let formData = new FormData(document.getElementById('feedbackForm'));
        let button = document.getElementById('sendButton');

        console.log('Button before change:', button.innerText);
        button.innerText = 'Отправка...';
        console.log('Button after change:', button.innerText);

        fetch('{% url 'app_kiberclub:review_from_parent' %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    document.getElementById('message').innerText = data.message;
                    button.innerText = 'Отправить';
                }
            })
            .catch(error => {
                console.error('Error:', error);
                button.innerText = 'Отправить';
            });
    }
</script>

</body>
</html>

templates/app_kiberclub/error_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Что-то не так...</title>
    {% if is_iphone %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/error_page_style_iphone.css' %}">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/error_page_style.css' %}">
    {% endif %}
</head>
<body>
    <p>Ой... Что-то пошло не так...</p>
    <img src="{% static 'img/error.png' %}" id="errorImg" alt="Ошибка">
</body>
</html>

templates/app_kiberclub/greetings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% if is_iphone %}
        <link rel="stylesheet" href="{% static 'styles/start_page_style_iphone.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'styles/start_page_style.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'styles/spinner_style.css' %}">
    <script type="text/javascript" src="https://telegram.org/js/telegram-web-app.js"></script>
</head>

<body>
<center>
    <div id="loader"></div>
</center>
<div id="mainDiv">
    <section id="main">
        <p>Добро пожаловать <br> в KIBERhub!</p>
        <a href="{% url 'app_kiberclub:choose_child' %}" id="start-link">Давайте начнем</a>
        <img src="{% static 'img/start.png' %}" id="startImg" alt="Старт">
        <p id="text">KIBERhub - это личный кабинет Вашего ребенка, в котором вы сможете посмотреть количество заработанных киберонов, перейти в кабинет по предзаказу товаров к предстающему КиберШопу, узнать тему занятий и получить обратную связь от тьютора
        </p>
    </section>
</div>

</body>
<script>
    window.Telegram.WebApp.ready();
    window.Telegram.WebApp.expand();

    window.addEventListener('DOMContentLoaded', function () {

        document.getElementById("loader").style.display = 'block';
        document.getElementById("mainDiv").style.display = 'none';

        const initData = window.Telegram.WebApp.initData;
        const csrfToken = '{{ csrf_token }}';
        if (initData) {
            fetch('/kiberclub/save_init_data/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({initData: initData})
            })
                .then(response => response.json())
                .then(data => {
                    console.log('InitData отправлены:', data);
                    document.getElementById("loader").style.display = 'none';
                    document.getElementById("mainDiv").style.display = 'block';
                })
                .catch((error) => console.error('Ошибка:', error));
        } else {
            console.log("Telegram WebApp is not available");
            document.getElementById("loader").style.display = 'block';
            document.getElementById("mainDiv").style.display = 'none';
        }
    });
</script>
<script>
    document.getElementById('start-link').addEventListener('click', function (event) {
        event.preventDefault();  // Отменяем стандартное поведение ссылки

        const contentElement = document.getElementById("main");
        const loaderElement = document.getElementById("loader");
        loaderElement.style.display = 'block';
        contentElement.style.display = 'none';

        fetch(this.href, {
            method: 'GET',
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
            .then(response => {
                loaderElement.style.display = 'none';
                contentElement.style.display = 'none';

                if (response.ok) {
                    window.location.href = this.href;
                } else {
                    alert('Произошла ошибка. Пожалуйста, попробуйте снова.');
                }
            })
            .catch(error => {
                document.getElementById('loader').classList.remove('visible');
                document.getElementById('loader').classList.add('hidden');
                alert('Ошибка соединения. Пожалуйста, попробуйте снова.');
            });
    });
</script>
</html>

templates/app_kiberclub/sign_in.html
<!DOCTYPE html>
<html>
<head>
    <title>Вход</title>
    <link rel="stylesheet" type="text/css" href="sign_in_style.css">
    <script type = "module" src="./load_animation.js"></script>
    <script type = "module" src="./set_sign_in_style.js"></script>
</head>
<body>
    <input type="tel" id="phone" name="phone" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}" placeholder="+375XXXXXXXXX">
    <button id="reg">ВОЙТИ</button>
    <div class="loader"></div>
</body>