app_accounts/urls.py
from django.urls import path
from app_accounts.views import signup, login_view, logout_view

app_name = 'app_accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

app_kibershop/urls.py
from django.urls import path
from app_kibershop.views import catalog, add_to_cart, cart, remove_from_cart, cart_plus, cart_minus, make_order, profile_page


app_name = 'app_kibershop'


urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', cart, name='cart'),
    path('remove_from_cart/<int:cart_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart_plus/<int:cart_id>/', cart_plus, name='cart_plus'),
    path('cart_minus/<int:cart_id>/', cart_minus, name='cart_minus'),
    path('make_order/', make_order, name='make_order'),
    path('profile_page/', profile_page, name='profile_page'),
]

tg_kiberclub/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kiberclub/', include('app_kiberclub.urls')),
    path('accounts/', include('app_accounts.urls')),
    path('admin_management/', include('app_admin_management.urls')),
    path('kibershop/', include('app_kibershop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_kibershop/models.py
from django.db import models
from app_kiberclub.models import UserData


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    objects = models.Manager()

    class Meta:
        db_table = 'Category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


# Create your models here.
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', blank=True, null=True)
    name = models.CharField(max_length=255, verbose_name='Название')
    price = models.IntegerField(verbose_name='Цена')
    image = models.ImageField(upload_to='item_images/', verbose_name='Изображение', blank=True, null=True)
    quantity_in_stock = models.PositiveSmallIntegerField(default=1, verbose_name="Количество на складе")
    in_stock = models.BooleanField(default=True, verbose_name='В наличии')
    objects = models.Manager()

    class Meta:
        db_table = 'Product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name


class CartQuerySet(models.QuerySet):
    def total_quantity(self):
        return sum(item.quantity for item in self)

    def total_sum(self):
        return sum(item.cart_item_price() for item in self)

class Cart(models.Model):
    user = models.ForeignKey(UserData, on_delete=models.CASCADE, related_name='cart', verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name="Количество", blank=True, null=True)
    objects = CartQuerySet.as_manager()

    class Meta:
        db_table = 'Cart'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return f'Корзина: {self.user.username} | Продукт: {self.item.name}'

    def cart_item_price(self):
        return self.product.price * self.quantity

    def item_quantity(self):
        return self.quantity


class Order(models.Model):
    user = models.ForeignKey(UserData, on_delete=models.CASCADE, verbose_name='Пользователь')
    objects = models.Manager()

    class Meta:
        db_table = 'Order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ: {self.id} | Телефон: {self.user.phone_number}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name="Количество")
    models.PositiveSmallIntegerField(default=1, verbose_name="Количество")
    objects = models.Manager()

    class Meta:
        db_table = 'OrderItem'
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказа'

    def __str__(self):
        return f'Заказ: {self.id} | Продукт: {self.product.name}'

app_kibershop/views.py
import pandas as pd
from django.contrib import messages
from django.db.models import Sum, F
from django.shortcuts import render, redirect

from app_kiberclub.models import UserData
from app_kiberclub.views import GoogleSheet
from app_kibershop.models import Product, Category, Cart, OrderItem, Order


from logger_config import get_logger
logger = get_logger()

CREDENTIALS_FILE = 'kiberone-tg-bot-a43691efe721.json'


# Create your views here.
def catalog(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'app_kibershop/catalog.html', context=context)


def add_to_cart(request, product_id):
    if request.method != 'POST':
        return redirect(request.META.get('HTTP_REFERER'))

    user_id = request.session.get('user_tg_id')
    if not user_id:
        messages.error(request, 'Вы не авторизованы', extra_tags='danger')
        return redirect(request.META.get('HTTP_REFERER'))

    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        messages.error(request, 'Товар не найден', extra_tags='danger')
        return redirect(request.META.get('HTTP_REFERER'))

    try:
        user = UserData.objects.get(tg_id=user_id)
    except UserData.DoesNotExist:
        messages.error(request, 'Вы не авторизованы', extra_tags='danger')
        return redirect(request.META.get('HTTP_REFERER'))

    cart_item, created = Cart.objects.get_or_create(
        user=user,
        product=product,
    )

    if not created:
        cart_item.quantity += 1
        cart_item.save()

    return redirect(request.META.get('HTTP_REFERER'))


def cart(request):
    return render(request, 'app_kibershop/cart_page.html')


def remove_from_cart(request, cart_id):
    cart_item = Cart.objects.get(id=cart_id)
    cart_item.delete()
    return redirect(request.META.get('HTTP_REFERER'))


def cart_minus(request, cart_id):
    cart_item = Cart.objects.get(id=cart_id)
    if cart_item.quantity == 1:
        return redirect(request.META.get('HTTP_REFERER'))
    cart_item.quantity -= 1
    cart_item.save()
    return redirect(request.META.get('HTTP_REFERER'))


def cart_plus(request, cart_id):
    cart_item = Cart.objects.get(id=cart_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect(request.META.get('HTTP_REFERER'))


def make_order(request):
    try:
        if request.method == 'POST':
            logger.info("Начало обработки заказа.")

            try:
                user_tg_id = request.session.get('user_tg_id')
                if user_tg_id is None:
                    raise ValueError("user_tg_id is not in session")
                user_in_db = UserData.objects.get(tg_id=user_tg_id)
                logger.info(f"Пользователь найден: {user_in_db}")
            except UserData.DoesNotExist:
                logger.error("Пользователь не найден.")
                return redirect(request.META.get('HTTP_REFERER'))
            except ValueError as ve:
                logger.error(f"Ошибка значения: {ve}")
                return redirect(request.META.get('HTTP_REFERER'))
            except Exception as e:
                logger.error(f"Ошибка при получении пользователя: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            try:
                user_orders = Order.objects.filter(user=user_in_db)
                if user_orders.exists():
                    user_kiberons = user_in_db.kiberons_count_after_orders
                else:
                    user_kiberons = user_in_db.kiberons_count
            except Exception as e:
                logger.error(f"Ошибка при получении заказов пользователя: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            try:
                total_sum = Cart.objects.filter(user=user_in_db).total_sum()
                logger.info(f"Сумма заказа: {total_sum}")
                logger.info(f"Кибероны пользователя: {user_kiberons}")
            except Exception as e:
                logger.error(f"Ошибка при расчете суммы заказа: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            if user_kiberons < total_sum:
                logger.error("Недостаточно киберонов для оформления заказа.")
                messages.error(request, 'Недостаточно киберонов', extra_tags='danger')
                return redirect(request.META.get('HTTP_REFERER'))

            try:
                if user_orders.exists():
                    user_in_db.kiberons_count_after_orders = user_in_db.kiberons_count_after_orders - total_sum
                else:
                    user_in_db.kiberons_count_after_orders = user_in_db.kiberons_count - total_sum
                user_in_db.save()
                logger.info(f"Обновлен баланс пользователя после заказа: {user_in_db.kiberons_count_after_orders}")
            except Exception as e:
                logger.error(f"Ошибка при обновлении баланса пользователя: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            try:
                order = Order.objects.create(user=user_in_db)
                logger.info(f"Создан заказ: {order}")
            except Exception as e:
                logger.error(f"Ошибка при создании заказа: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            for item in Cart.objects.filter(user=user_in_db):
                try:
                    product_in_db = Product.objects.get(id=item.product.id)
                    logger.info(f"Продукт найден: {product_in_db}")
                except Product.DoesNotExist:
                    logger.error(f"Продукт не найден: {item.product.id}")
                    return redirect(request.META.get('HTTP_REFERER'))
                except Exception as e:
                    logger.error(f"Ошибка при получении продукта: {e}")
                    return redirect(request.META.get('HTTP_REFERER'))

                try:
                    if product_in_db.quantity_in_stock < item.quantity:
                        logger.error(f"Недостаточно товара на складе: {product_in_db.name}")
                        messages.error(request, f'Недостаточно товара на складе: {product_in_db.name}', extra_tags='danger')
                        return redirect(request.META.get('HTTP_REFERER'))

                    product_in_db.quantity_in_stock -= item.quantity
                    if product_in_db.quantity_in_stock == 0:
                        product_in_db.in_stock = False
                    product_in_db.save()
                    logger.info(f"Обновлены данные продукта: {product_in_db}")
                except Exception as e:
                    logger.error(f"Ошибка при обновлении данных продукта: {e}")
                    return redirect(request.META.get('HTTP_REFERER'))

                try:
                    OrderItem.objects.create(
                        order=order,
                        product=item.product,
                        quantity=item.quantity,
                    )
                    logger.info(f"Создан элемент заказа: {item.product.name} x {item.quantity}")
                except Exception as e:
                    logger.error(f"Ошибка при создании элемента заказа: {e}")
                    return redirect(request.META.get('HTTP_REFERER'))

            logger.info(f"Обновлен баланс пользователя после заказа: {user_in_db.kiberons_count_after_orders}")

            try:
                spreadsheet_url = request.session.get('spreadsheet_url')
                worksheet_name = request.session.get('worksheet_name')
                logger.info(f"URL таблицы: {spreadsheet_url}, Имя листа: {worksheet_name}")
            except Exception as e:
                logger.error(f"Ошибка при получении URL таблицы или имени листа: {e}")
                return redirect(request.META.get('HTTP_REFERER'))

            try:
                google_sheet = GoogleSheet(CREDENTIALS_FILE, spreadsheet_url, worksheet_name)
                df = google_sheet.load_data_from_google_sheet()
                if df is None:
                    logger.error("Не удалось загрузить данные из Google Sheets.")
                    return redirect('app_kiberclub:error_page')
            except Exception as e:
                logger.error(f"Ошибка при загрузке данных из Google Sheets: {e}")
                return redirect('app_kiberclub:error_page')

            try:
                row_index = df[df['ID ребенка'] == user_in_db.user_crm_id].index
                if row_index.empty:
                    raise ValueError(f"Child with ID {user_in_db.user_crm_id} not found in the worksheet")

                row_number = row_index[0] + 2  # +2, потому что индексы DataFrame начинаются с 0, а индексы Google Sheets с 1
                worksheet = google_sheet.spreadsheet.worksheet(google_sheet.worksheet_name)
                current_data = worksheet.cell(row_number, df.columns.get_loc('Кибершоп') + 1).value
                new_data = '\n'.join(
                    [
                        f'\nТовар: {item.product.name} | Количество: {item.quantity} | Кибероны: {item.product.price * item.quantity}'
                        for item in Cart.objects.filter(user=user_in_db)
                    ]
                )
                combined_data = f"{current_data}\n{new_data}"
                worksheet.update_cell(row_number, df.columns.get_loc('Кибершоп') + 1, combined_data)

                logger.info("Данные успешно сохранены в Google Sheets.")
            except UnicodeEncodeError as uee:
                logger.error(f"Ошибка кодировки: {uee}")
                return redirect('app_kiberclub:error_page')
            except Exception as e:
                logger.error(f"Ошибка при сохранении данных в Google Sheets: {e}")
                return redirect('app_kiberclub:error_page')

            try:
                Cart.objects.filter(user=user_in_db).delete()

templates/app_kibershop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Корзина</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/header_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/footer_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/fixed_cart_button_style.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="catalog_style.css"> -->
    <!-- <link rel="stylesheet" type="text/css" href="fixed_cart_button_style.css"> -->
    <!-- <meta name="viewport" content="width=device-width"> -->
    {% block head %}
    {% endblock %}
</head>

<header style="background-image: url({% static 'img/kibershop/waves.svg' %})">
    <section id="headerLine">
        <a href="{% url 'app_kibershop:catalog' %}"><img src="{% static 'img/kibershop/logo.jpg' %}" id="logoImg"></a>
        <a href="{% url 'app_kibershop:catalog' %}" id="toCatalog">Каталог</a>
        <!-- <button><img src="insta logo.svg" class="iconImg"></button>
        <button><img src="tt logo.svg" class="iconImg"></button> -->
        <a href="{% url 'app_kibershop:cart' %}"><img src="{% static 'img/kibershop/cart_logo.svg' %}"
                                                      class="iconImg"></a>
        <section id="headerButtons">
            <a href="{% url 'app_kibershop:profile_page' %}"><img src="{% static 'img/kibershop/icon_profile.svg' %}" id="profileImg" class="iconImg"></a>
        </section>
    </section>
    {% block header %}
    {% endblock %}
</header>

{% block content %}

{% endblock %}


<footer style="background-image: url({% static 'img/kibershop/waves_footer.svg' %})">
    <section id="companyInfo">
        <i>OOO «КИБЕРуан БЕЛ» РБ,</i>
        <i>УНП 193397920</i>
    </section>
    <img src="{% static 'img/kibershop/logo.jpg' %}" id="logoImg" alt="logo">
    {% block footer %}
    {% endblock %}
</footer>
</html>

templates/app_kibershop/cart_page.html
{% extends 'app_kibershop/base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/order_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/cart_page_style.css' %}">

{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <body>
    <section id="titleSection">
        <p id="titleText">Корзина</p>
    </section>
    {% include 'app_kibershop/notifications.html' %}
    <section id="orderProducts">
        {% for cart in carts %}
            <div class="orderProductCard">
                <img src="{{ cart.product.image.url }}" class="orderProductImg" alt="item_image">
                <!-- <b><p class="cartProductName">Ноутбук</p></b> -->
                <section class="buttonsRowSection">
                    <a href="{% url 'app_kibershop:cart_minus' cart.id %}" class="signButton">-</a>
                    <p class="productCount">{{ cart.quantity }}</p>
                    <a href="{% url 'app_kibershop:cart_plus' cart.id %}" class="signButton">+</a>
                </section>
                <section class="orderSection">
                    <p class="orderProductPrice"><b>{{ cart.cart_item_price }}К</b></p>
                    <!--  <button class="orderButton">Предзаказ</button>  -->
                </section>
                <section class="removeButtonSection">
                    <a href="{% url 'app_kibershop:remove_from_cart' cart.id %}"><img src="{% static 'img/kibershop/remove.svg' %}" class="removeButton"></a>
                </section>
            </div>
        {% endfor %}
    </section>

    <section id="fullOrderInfoSection">
        <div id="fullOrderInfo">
            <p id="orderProductsCount">Товары: <b>{{ carts.total_quantity }}</b> шт.</p>
            <p id="orderKiberonsCount">Итого: <b>{{ carts.total_sum }}</b> К</p>
        </div>
        <form id="orderForm" action="{% url 'app_kibershop:make_order' %}" method="post">
            {% csrf_token %}
            <button type="submit" id="fullOrderButton" disabled><img src="{% static 'img/kibershop/money.svg' %}" id="fullOrderButtonImg">Предзаказ</button>
        </form>

    </section>
    </body>
    <script>
        //document.getElementById('fullOrderButton').addEventListener('click', function (event) {
        //    event.preventDefault();
        //    this.innerHTML = 'Обработка…';
        //    document.getElementById('orderForm').submit();
        //});
    </script>
{% endblock %}

{% block footer %}

{% endblock %}

templates/app_kibershop/catalog.html
{% extends 'app_kibershop/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/catalog_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/running_line.css' %}">
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <body>
    <section id="fixedCartSection">
        <p id="productInCartCount">{% if carts.total_quantity %}{{ carts.total_quantity }}{% else %}0{% endif %}</p>
        <a href="{% url 'app_kibershop:cart' %}" id="fixedCartButton">
            <img src="{% static 'img/kibershop/cart_logo.svg' %}" id="fixedCartButtonImg" alt="Корзина">
        </a>
    </section>
    <section id="kibershopText">
        <h1 style="color: #06B9BE">K</h1>
        <h1 style="color: #FFCD26">I</h1>
        <h1 style="color: #8C271F">B</h1>
        <h1 style="color: #9C9C9C">E</h1>
        <h1 style="color: #1C546D">R</h1>
        <h1 style="margin-left: 20px">SHOP</h1>
    </section>


    <section class="productListSection">
        <div style="margin-top: -3vw;" id="warning">
            <p class="warningText">ПРЕДЗАКАЗ ЗАКРЫТ! ВАШИ ЗАКАЗЫ ВЫ МОЖЕТЕ ОТСЛЕДИТЬ ПЕРЕЙДЯ ПО КНОПКЕ ПРОФИЛЯ В ШАПКЕ</p>
        </div>
        {% for category in categories %}
            <section class="sectionTitle">
                <span>{{ category.name }}</span>
            </section>
            <section class="productsSection">
                <div class="productsRow" style="display: grid; grid-template-columns: repeat(2, 1fr);">
                    {% for product in category.product_set.all %}
                        {% if product.in_stock %}
                            <form action="{% url 'app_kibershop:add_to_cart' product.id %}" method="post">
                                {% csrf_token %}
                                <div class="productCard">
                                    <img src="{{ product.image.url }}" class="productImg"
                                         alt="{{ product.name }}">
                                    <section class="productInfo">
                                        <section class="productInfoText">
                                            <p class="productName">{{ product.name }}</p>
                                            <p class="productPrice">{{ product.price }}К</p>
                                        </section>
                                        <section class="buttonsRowSection">
                                            <button class="cartButton" id="cartButton"><img
                                                    src="{% static 'img/kibershop/cart_logo.svg' %}"
                                                    class="iconImg" alt="Корзина"></button>
                                        </section>
                                    </section>
                                </div>
                            </form>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>
        {% endfor %}
    </section>

    </body>

{% endblock %}



{% block footer %}

{% endblock %}

templates/app_kibershop/notifications.html
<section>
    {% if messages %}
    	{% for message in messages %}
    		<p id="errorText">{{ message }}</p>
    	{% endfor %}
    {% endif %}
</section>

templates/app_kibershop/profile_page.html
{% extends 'app_kibershop/base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/order_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/kibershop_styles/profile_style.css' %}">
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
<body>
    <section id="titleSection">
        <p id="titleText">Мои покупки</p>
    </section>
    <section id="orderProducts">
        {% for order_item in order_items %}
        	<div class="orderProductCard">
            <img src="{{ order_item.product.image.url }}" class="orderProductImg">
            <!-- <b><p class="cartProductName">Ноутбук</p></b> -->
            <section class="orderSection">
                <p class="orderProductPrice"><b>{{ order_item.quantity }} шт.</b></p>
                <p class="orderProductPrice"><b>{{ order_item.product.price }}К</b></p>
                <p class="orderProductStatus"><b>Заказано</b></p>
            </section>
        </div>
        {% endfor %}
    </section>


    <section id="fullOrderInfoSection">
        <div id="fullOrderInfo">
            <p id="orderProductsCount">Товары: <b>{{ total_quantity }} шт.</b></p>
            <p id="orderKiberonsCount">Итого: <b>{{ total_sum }} К</b></p>
        </div>
        <p id="orderHint">*Для изменения заказа свяжитесь с Вашим менеджером</p>
    </section>
</body>
{% endblock %}

{% block footer %}

{% endblock %}